site_name: AWX Operator
site_description: Kubernetes operator for AWX deployment

nav:
  - Home: index.md
  - Overview: overview.md
  - Usage: usage.md

plugins:
  - techdocs-core
  - d2:
      theme: 4
