site_name: Splunk Enterprise
site_description: Machine data analytics and security monitoring

nav:
  - Home: index.md
  - Overview: overview.md
  - Usage: usage.md

plugins:
  - techdocs-core
  - d2:
      theme: 4
