---
galaxy_info:
  author: DevOps Team
  description: Install and configure Nginx webserver
  company: Cloud Sandbox
  license: MIT
  min_ansible_version: '2.12'

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'

  galaxy_tags:
    - nginx
    - webserver
    - web
    - proxy
    - reverseproxy
    - ssl
    - tls

dependencies: []
