site_name: Docker Host Playbook
site_description: Ansible playbook for setting up Docker on Linux hosts

nav:
  - Home: index.md
  - Overview: overview.md
  - Usage: usage.md

plugins:
  - techdocs-core
  - d2:
      theme: 4
