site_name: ${{ values.name }}
site_description: ${{ values.description }}

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Test Scenarios: test-scenarios.md
  - Thresholds: thresholds.md
  - CI/CD: ci-cd.md

plugins:
  - techdocs-core
