site_name: ${{ values.name }}
site_description: ${{ values.description }}

nav:
  - Home: index.md
  - DAG Structure: dag-structure.md
  - Configuration: configuration.md
  - Testing: testing.md
  - Deployment: deployment.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
