site_name: ${{ values.name }}
site_description: ${{ values.description }}

nav:
  - Home: index.md
  - API Reference: api.md
  - Development: development.md
  - Deployment: deployment.md

plugins:
  - techdocs-core
