site_name: "${{ values.name }}"
site_description: "Terraform module documentation for ${{ values.name }}"
docs_dir: docs
repo_url: https://github.com/${{ values.owner }}/${{ values.name }}

nav:
  - Home: index.md

plugins:
  - techdocs-core
