site_name: ${{ values.name }}
site_description: ${{ values.description }}

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Writing Tests: writing-tests.md
  - Page Objects: page-objects.md
  - CI/CD: ci-cd.md

plugins:
  - techdocs-core
